config/routes.rb
Rails.application.routes.draw do
  resources :word_news
  resources :word_fixes
  resources :words
  resources :word_categories
  telegram_webhook TelegramWebhooksController
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :word_category, optional: true

  STATUS_LIST = [:published, :moderated, :blocked]

  enum status: STATUS_LIST

  def self.find_word(word)
    word.downcase!
    Word.where(status: :published).where('"kub" = ? OR "rus" = ?', word, word).first
  end

  def self.in_moderate?(word)
    word.downcase!
    Word.where(status: :moderated).where('"kub" = ? OR "rus" = ?', word, word).count > 0
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  def index
    @words = Word.all
  end

  # GET /words/1
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  def create
    @word = Word.new(word_params)

    if @word.save
      redirect_to @word, notice: 'Word was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /words/1
  def update
    if @word.update(word_params)
      redirect_to @word, notice: 'Word was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /words/1
  def destroy
    @word.destroy
    redirect_to words_url, notice: 'Word was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def word_params
      params.require(:word).permit(:rus, :kub, :word_category_id, :body)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rus %>
    <%= form.text_field :rus, id: :word_rus %>
  </div>

  <div class="field">
    <%= form.label :kub %>
    <%= form.text_field :kub, id: :word_kub %>
  </div>

  <div class="field">
    <%= form.label :word_category_id %>
    <%= form.text_field :word_category_id, id: :word_word_category_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :word_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Rus</th>
      <th>Kub</th>
      <th>Word category</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.rus %></td>
        <td><%= word.kub %></td>
        <td><%= word.word_category %></td>
        <td><%= word.body %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rus:</strong>
  <%= @word.rus %>
</p>

<p>
  <strong>Kub:</strong>
  <%= @word.kub %>
</p>

<p>
  <strong>Word category:</strong>
  <%= @word.word_category %>
</p>

<p>
  <strong>Body:</strong>
  <%= @word.body %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>