config/routes.rb
Rails.application.routes.draw do
  resources :word_news
  resources :word_fixes
  resources :words
  resources :word_categories
  telegram_webhook TelegramWebhooksController
end

app/models/word_category.rb
class WordCategory < ApplicationRecord
end

app/controllers/word_categories_controller.rb
class WordCategoriesController < ApplicationController
  before_action :set_word_category, only: [:show, :edit, :update, :destroy]

  # GET /word_categories
  def index
    @word_categories = WordCategory.all
  end

  # GET /word_categories/1
  def show
  end

  # GET /word_categories/new
  def new
    @word_category = WordCategory.new
  end

  # GET /word_categories/1/edit
  def edit
  end

  # POST /word_categories
  def create
    @word_category = WordCategory.new(word_category_params)

    if @word_category.save
      redirect_to @word_category, notice: 'Word category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /word_categories/1
  def update
    if @word_category.update(word_category_params)
      redirect_to @word_category, notice: 'Word category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /word_categories/1
  def destroy
    @word_category.destroy
    redirect_to word_categories_url, notice: 'Word category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word_category
      @word_category = WordCategory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def word_category_params
      params.require(:word_category).permit(:name, :body)
    end
end

app/helpers/word_categories_helper.rb
module WordCategoriesHelper
end

app/views/word_categories/_form.html.erb
<%= form_with(model: word_category, local: true) do |form| %>
  <% if word_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word_category.errors.count, "error") %> prohibited this word_category from being saved:</h2>

      <ul>
      <% word_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :word_category_name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :word_category_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/word_categories/edit.html.erb
<h1>Editing Word Category</h1>

<%= render 'form', word_category: @word_category %>

<%= link_to 'Show', @word_category %> |
<%= link_to 'Back', word_categories_path %>

app/views/word_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Word Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @word_categories.each do |word_category| %>
      <tr>
        <td><%= word_category.name %></td>
        <td><%= word_category.body %></td>
        <td><%= link_to 'Show', word_category %></td>
        <td><%= link_to 'Edit', edit_word_category_path(word_category) %></td>
        <td><%= link_to 'Destroy', word_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word Category', new_word_category_path %>

app/views/word_categories/new.html.erb
<h1>New Word Category</h1>

<%= render 'form', word_category: @word_category %>

<%= link_to 'Back', word_categories_path %>

app/views/word_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @word_category.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @word_category.body %>
</p>

<%= link_to 'Edit', edit_word_category_path(@word_category) %> |
<%= link_to 'Back', word_categories_path %>